pollr/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'pollr.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', include('polls.urls')),
    url(r'^polls/', include('polls.urls', namespace="polls")),
    url(r'^admin/', include(admin.site.urls)),
]

polls/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    # ex: /polls/
    url(r'^$', views.index, name='index'),
    # ex: /polls/5/
    url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
    # ex: /polls/5/results/
    url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
    # ex: /polls/5/vote/
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
    # ex: /polls/add/
    url(r'^create/$', views.Create.as_view(), name='create'),
    # ex: /polls/5/delete/
    url(r'^(?P<question_id>[0-9]+)/delete/$', views.delete, name='delete'),
]

polls/models.py
# Create your models here.
import datetime

from django.db import models
from django.utils import timezone
from django.forms import ModelForm

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):              # __unicode__ on Python 2
    	return self.question_text
    def was_published_recently(self):
	    return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
	# admin settings #
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'
    
# not in use yet #
class QuestionForm(ModelForm):
    class Meta:
        model = Question
        fields = ['question_text']


class Choice(models.Model):
    question = models.ForeignKey(Question)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):              # __unicode__ on Python 2
    	return self.choice_text

# not in use yet #
class ChoiceForm(ModelForm):
    class Meta:
        model = Choice
        fields = ['choice_text']

polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, Http404
#from django.template import RequestContext, loader
from django.core.urlresolvers import reverse
from django.views.generic import View
from django.utils import timezone

# Create your views here.
from .models import Question, Choice, QuestionForm, ChoiceForm

""""
def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    template = loader.get_template('polls/index.html')
    context = RequestContext(request, {
        'latest_question_list': latest_question_list,
    })
    return HttpResponse(template.render(context))
"""

def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'polls/index.html', context)

def detail(request, question_id):
    try:
        question = Question.objects.get(pk=question_id)
    except Question.DoesNotExist:
        raise Http404("Question does not exist")
    return render(request, 'polls/detail.html', {'question': question})

"""
def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question': question})
"""
    
def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})

def vote(request, question_id):
    p = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = p.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': p,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(p.id,)))
    
class Create(View):
    def get(self, request):
        form = QuestionForm() # not used #
        return render(request, 'polls/create.html', {
            #'form': form#
        })
    def post(self, request):
        #print request.POST.__str__()
        form = request.POST
        title = request.POST.get("title")
        if title:
            question = Question(question_text=title, pub_date=timezone.now())
            print "print", question.question_text, question.pub_date
            question.save()
        else:
            return render(request, 'polls/create.html', {
            })                
#        print title
        return HttpResponseRedirect(reverse('polls:index'))

def delete(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if question:
        question.delete()
    return HttpResponseRedirect(reverse('polls:index'))

polls/templates/polls/base.html
{% load staticfiles %}

<html>
<head>
<title>Pollr - Make Your Choice</title>

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/css/style.css' %}" />
{% endblock %}

{% block js %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
<script src="{% static 'polls/js/base.js' %}"></script>
<script src="{% static 'polls/js/polls.js' %}"></script>
{% endblock %}

</head>
<body>


{% block header %}
<header>
<div class="header-corpname"><a href="/">POLLR</a></div>
<a href="{% url 'polls:create' %}">Create</a>
</header>
{% endblock %}

{% block main %}
{% endblock %}

polls/templates/polls/create.html
{% extends "polls/base.html" %}

{% block main %}
<h1>Create Poll</h1>


<form action="{% url 'polls:create' %}" method="post">
{% csrf_token %} {# security for internal posting #}

<div class="inputField">
<label>Question Title</label>
<input type="text" name="title" placeholder="Do you love me?" />
</div>

<div class="inputField">
<label>Choice 1</label>
<input type="text" name="choice1" placeholder="Yes" />
</div>

<div class="inputField">
<label>Choice 2</label>
<input type="text" name="choice2" placeholder="No" />
</div>

<div class="inputField">
<label>Choice 3</label>
<input type="text" name="choice3" placeholder="Maybe" />
</div>

<div class="inputField">
<input type="submit" value="Save" />
</div>

</form>

{% endblock %}

polls/templates/polls/detail.html
{% extends "polls/base.html" %}

{% block main %}
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %} {# security for internal posting #}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>
{% endblock %}

polls/templates/polls/index.html
{% extends "polls/base.html" %}

{% block main %}
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a> [<a class="poll-delete" href="{% url 'polls:delete' question.id %}">x</a>]</li>
        {#<li><a href="/polls/{{ question.id }}/">{{ question.question_text }}</a></li>#}

    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}
{% endblock %}

polls/templates/polls/results.html
{% extends "polls/base.html" %}

{% block main %}
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>
{% endblock %}